#!/bin/sh

# This little trick allows me to put comments, the
# shell won't allow them after a \ line continuation.
# Plot output saved into "runme.ps".

(
    cmd=""
    while read arg; do
	cleaned=`echo "$arg" | sed -e 's/\#.*$//' -e 's/^[[:space:]]*//g' -e 's/[[:space:]]*$//g'`  # remove comments and whitespace
	if [ "x$cleaned" != "x" ]; then  # make sure not blank
	    if [ "x$cmd" != "x" ]; then  # this avoids a leading space
                cmd="$cmd $cleaned"
	    else
	        cmd="$cleaned"
            fi
	fi
    done
    echo "Executing: $cmd"  # to see what it did!
    $cmd <<EOP
runme.ps/cps
EOP
) <<"EOD"
# This is the actual command
../ebmc
-f I\\dMEarth\\u,I\\dBessell\\u   # pgplot markup for filter names in plots
-k 5                              # 5-sigma clip
#-m mc-spot1                      # do MC, output to mc-spot1* (DISABLED)
#-l mc-spot1                      # load MC output from mc-spot1 (DISABLED)
-n 2000000                        # default no. MC sims
-O                                # "old" light curve file format
pset-spot1                        # parameter file
mearth-ooe.lc,air,cm,err                  # input files filter 1 (I_C)
mearth-20101118.lc,useair,usecm,err  
mearth-20110208.lc,useair,usecm,err  
mearth-20110501.lc,useair,usecm,err  
lc1=mearth-pri-20100402.lc,err            # input files filter 2 (I_Bessell)
lc1=hankasalmi-20110115.lc,err  
lc1=clay-20100607.lc,air,err  
lc1=clay-20101008.lc,air,err  
lc1=clay-20101118.lc,air,err  
lc1=clay-20101229.lc,air,err  
rv1=lspm1112+7626.rv1,4800,err=0.12,wt    # input files RV
rv2=lspm1112+7626.rv2,4800,err=0.24,wt  
lrat=lspm1112+7626.lrat                   # spectroscopic light ratio
EOD

