MODULE EB
DESCRIPTION Eclipsing binary models
VERSION 1.0
SOURCE Jonathan Irwin
BUILD_DATE 20170217
FUNCTION EB_MODEL 0 IDL_MAXPARAMS KEYWORDS
FUNCTION EB_PHISEC 0 IDL_MAXPARAMS
FUNCTION EB_PHICONT 0 IDL_MAXPARAMS
FUNCTION EB_GETVDER 0 IDL_MAXPARAMS
